name: API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  # Necessário caso queira dar permissão de escrita para publicar no GitHub Pages (opcional)
  # id-token: write
  # pages: write

jobs:
  api-tests:
    name: Run API tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          distribution: oracle
          java-version: '27'
          cache: maven

      - name: Run tests
        run: bash ./mvnw --batch-mode --no-transfer-progress -DfailIfNoTests=true test

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: allure-report

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_report: allure-report
          storage_type: s3
          keep_reports: 20

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report-artifact
          path: allure-report